apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      namespace: "shopping"
    spec:
      containers:
      - name: frontend
        image: kimkyusoo/frontend:1204
        ports:
        - containerPort: 8080